import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { BrainCircuit, Volume2, VolumeX, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

/**
 * Copilot tip structure as generated by Gemini AI.
 * Each tip has a trigger label (Strategy Pattern) that determines
 * when the tip should be displayed based on delivery progress.
 */
interface CopilotTip {
  message: string;
  trigger: 'ON_START' | 'AFTER_DELIVERY_3' | 'HALFWAY' | 'NEAR_END' | 'ALL_DONE' | 'GENERAL';
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
}

interface DeliveryStats {
  delivered: number;
  pending: number;
  total: number;
}

interface DriverCopilotBannerProps {
  tipsJson: string;
  stats: DeliveryStats;
  driverName?: string;
}

/**
 * Strategy Pattern — Trigger Evaluation Map.
 * Each trigger has a predicate function that evaluates whether
 * the current delivery stats match the conditions for showing the tip.
 */
const TRIGGER_STRATEGIES: Record<string, (stats: DeliveryStats) => boolean> = {
  'ON_START':         (s) => s.delivered === 0 && s.pending > 0,
  'AFTER_DELIVERY_3': (s) => s.delivered >= 3 && s.delivered < Math.floor(s.total / 2),
  'HALFWAY':          (s) => s.delivered >= Math.floor(s.total / 2) && s.pending > 2,
  'NEAR_END':         (s) => s.pending <= 2 && s.pending > 0,
  'ALL_DONE':         (s) => s.pending === 0 && s.delivered > 0,
  'GENERAL':          () => true,
};

const PRIORITY_COLORS: Record<string, { border: string; bg: string; icon: string }> = {
  'HIGH':   { border: 'border-l-red-500', bg: 'bg-red-50/80', icon: 'text-red-500' },
  'MEDIUM': { border: 'border-l-amber-500', bg: 'bg-amber-50/80', icon: 'text-amber-500' },
  'LOW':    { border: 'border-l-emerald-500', bg: 'bg-emerald-50/80', icon: 'text-emerald-500' },
};

const STORAGE_KEY = 'vibe-copilot-shown-tips';
const AUTO_DISMISS_MS = 12_000;

/**
 * DriverCopilotBanner — AI-powered delivery assistant banner.
 * 
 * Consumes pre-generated Gemini tips from the batch entity and
 * displays them progressively based on delivery progress.
 * Uses the Strategy Pattern for trigger evaluation and
 * Web Speech API for optional voice synthesis.
 */
export const DriverCopilotBanner: React.FC<DriverCopilotBannerProps> = ({
  tipsJson,
  stats,
  driverName,
}) => {
  const [activeTip, setActiveTip] = useState<CopilotTip | null>(null);
  const [isDismissed, setIsDismissed] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  // Parse tips from JSON string (defensive parsing)
  const tips: CopilotTip[] = useMemo(() => {
    try {
      const parsed = JSON.parse(tipsJson);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }, [tipsJson]);

  // Retrieve shown tips from localStorage to avoid repetition
  const getShownTips = useCallback((): Set<string> => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? new Set(JSON.parse(stored)) : new Set();
    } catch {
      return new Set();
    }
  }, []);

  const markTipAsShown = useCallback((trigger: string) => {
    const shown = getShownTips();
    shown.add(trigger);
    localStorage.setItem(STORAGE_KEY, JSON.stringify([...shown]));
  }, [getShownTips]);

  // Strategy Pattern execution: evaluate which tip should be active
  useEffect(() => {
    if (tips.length === 0 || isDismissed) return;

    const shownTips = getShownTips();

    // Find the first tip whose trigger matches current stats AND hasn't been shown
    const matchingTip = tips.find((tip) => {
      const strategy = TRIGGER_STRATEGIES[tip.trigger];
      if (!strategy) return false;
      if (shownTips.has(tip.trigger)) return false;
      return strategy(stats);
    });

    if (matchingTip && matchingTip.trigger !== activeTip?.trigger) {
      setActiveTip(matchingTip);
      setIsDismissed(false);
      markTipAsShown(matchingTip.trigger);
    }
  }, [stats, tips, isDismissed, getShownTips, markTipAsShown, activeTip?.trigger]);

  // Auto-dismiss timer
  useEffect(() => {
    if (!activeTip || isDismissed) return;
    const timer = setTimeout(() => setIsDismissed(true), AUTO_DISMISS_MS);
    return () => clearTimeout(timer);
  }, [activeTip, isDismissed]);

  /**
   * Web Speech API — Text-to-Speech synthesis.
   * Uses Colombian Spanish locale for natural pronunciation.
   */
  const speak = useCallback((text: string) => {
    if (!('speechSynthesis' in window)) return;
    
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'es-CO';
    utterance.rate = 0.95;
    utterance.pitch = 1.0;
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utterance);
  }, []);

  const handleDismiss = useCallback(() => {
    window.speechSynthesis?.cancel();
    setIsSpeaking(false);
    setIsDismissed(true);
  }, []);

  const handleSpeak = useCallback(() => {
    if (!activeTip) return;
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      speak(activeTip.message);
    }
  }, [activeTip, isSpeaking, speak]);

  const colors = activeTip ? PRIORITY_COLORS[activeTip.priority] || PRIORITY_COLORS['MEDIUM'] : PRIORITY_COLORS['MEDIUM'];

  return (
    <AnimatePresence>
      {activeTip && !isDismissed && (
        <motion.div
          initial={{ y: -20, opacity: 0, scale: 0.95 }}
          animate={{ y: 0, opacity: 1, scale: 1 }}
          exit={{ y: -20, opacity: 0, scale: 0.95 }}
          transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          className={`
            relative mx-auto max-w-md w-full mb-4
            ${colors.bg} backdrop-blur-xl
            border border-white/60 border-l-4 ${colors.border}
            rounded-2xl shadow-lg shadow-slate-200/50
            overflow-hidden
          `}
        >
          {/* Progress bar for auto-dismiss */}
          <motion.div
            initial={{ width: '100%' }}
            animate={{ width: '0%' }}
            transition={{ duration: AUTO_DISMISS_MS / 1000, ease: 'linear' }}
            className="absolute top-0 left-0 h-0.5 bg-slate-300/40"
          />

          <div className="flex items-start gap-3 p-4">
            {/* AI Brain Icon */}
            <div className={`shrink-0 mt-0.5 ${colors.icon}`}>
              <BrainCircuit size={20} className="animate-pulse" />
            </div>

            {/* Tip Content */}
            <div className="flex-1 min-w-0">
              <p className="text-[9px] font-black uppercase tracking-widest text-slate-400 mb-1">
                Copiloto IA
              </p>
              <p className="text-[13px] font-bold text-slate-800 leading-snug">
                {activeTip.message}
              </p>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-1 shrink-0">
              <button
                onClick={handleSpeak}
                className={`p-2 rounded-xl transition-all ${
                  isSpeaking
                    ? 'bg-slate-900 text-white shadow-md'
                    : 'text-slate-400 hover:bg-white/80 hover:text-slate-700'
                }`}
                title={isSpeaking ? 'Detener voz' : 'Escuchar'}
              >
                {isSpeaking ? <VolumeX size={16} /> : <Volume2 size={16} />}
              </button>
              <button
                onClick={handleDismiss}
                className="p-2 text-slate-300 hover:text-slate-600 rounded-xl hover:bg-white/80 transition-all"
              >
                <X size={14} />
              </button>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};
